/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package cafemanagementsystem;

import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 *
 * @author SandipKoirala
 */
public class CafeManagementSystem {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
    }

    /**
     *
     * @author SandipKoirala
     */
    public static class Home extends JFrame {

        /**
         * Creates new form Home
         */
        public Home() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings(value = "unchecked")
        private void initComponents() {
            jButton1 = new JButton();
            jButton2 = new JButton();
            jButton3 = new JButton();
            jButton4 = new JButton();
            jButton5 = new JButton();
            jButton6 = new JButton();
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            jButton1.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
            jButton1.setIcon(new ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
            jButton1.setText("Logout");
            jButton1.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            jButton2.setFont(new Font("Segoe UI", 1, 14)); // NOI18N 
            jButton2.setIcon(new ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
            jButton2.setText("Placed Order");
            jButton3.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
            jButton3.setText("View Billss and Order Details Placed");
            jButton4.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
            jButton4.setText("Change password");
            jButton4.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });
            jButton5.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
            jButton5.setText("Chane Security  Question");
            jButton6.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
            jButton6.setText("Exit");
            GroupLayout layout = new GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(20, 20, 20).addComponent(jButton1).addGap(109, 109, 109).addComponent(jButton2).addGap(115, 115, 115).addComponent(jButton3).addGap(109, 109, 109).addComponent(jButton4).addGap(122, 122, 122).addComponent(jButton5).addGap(112, 112, 112).addComponent(jButton6).addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
            layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(19, 19, 19).addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jButton2).addComponent(jButton1).addComponent(jButton3).addComponent(jButton4).addComponent(jButton5).addComponent(jButton6)).addContainerGap(722, Short.MAX_VALUE)));
            pack();
        } // </editor-fold>

        private void jButton1ActionPerformed(ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void jButton4ActionPerformed(ActionEvent evt) {
            // TODO add your handling code here:
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String[] args) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            //</editor-fold>
            /* Create and display the form */
            EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Home().setVisible(true);
                }
            });
        }
        // Variables declaration - do not modify
        private JButton jButton1;
        private JButton jButton2;
        private JButton jButton3;
        private JButton jButton4;
        private JButton jButton5;
        private JButton jButton6;
        // End of variables declaration
    }
    
}
